/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.administrador;

import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;

import controlador.administrador.GestionCategorias;
import controlador.administrador.GestionCuestionarios;
import controlador.administrador.GestionPreguntas;
import modelo.Cuestionario;
import vista.acceso.VentanaLogin;
import vista.administrador.dialogos.DialogoDatosCategoriaCuestionario;
import vista.juego.VentanaSeleccionarModoJuego;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 * @author fernando
 */
public class VentanaAdministrarCuestionarios extends javax.swing.JFrame {
    DefaultTableModel modelo;

    /**
     * Creates new form VentanaAdministrarCuestionarios
     */
    public VentanaAdministrarCuestionarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogoInformacionPregunta = new javax.swing.JDialog();
        panelInformacionPregunta = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        labelTextoPregunta = new javax.swing.JLabel();
        labelCategoriaPregunta = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelRespuestaCorrecta = new javax.swing.JLabel();
        labelRespuestaIncorrecta1Informacion = new javax.swing.JLabel();
        labelRespuestaIncorrecta2Informacion = new javax.swing.JLabel();
        labelRespuestaIncorrecta3Informacion = new javax.swing.JLabel();
        textoRespuestaCorrecta = new javax.swing.JTextField();
        textoRespuestaIncorrecta1 = new javax.swing.JTextField();
        textoRespuestaIncorrecta2 = new javax.swing.JTextField();
        textoRespuestaIncorrecta3 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnSalirDiaologoInformacion = new javax.swing.JButton();
        dialogoPreguntas = new javax.swing.JDialog();
        panelPrincipal1 = new javax.swing.JPanel();
        panelDialogoFila1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelDialogoFila2 = new javax.swing.JPanel();
        listaPreguntasDialogo = new javax.swing.JComboBox<>();
        listaCategoriasDialogo = new javax.swing.JComboBox<>();
        panelDialogoFila3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inputRespuestaCorrecta = new javax.swing.JTextField();
        inputRespuestaIncorrecta1 = new javax.swing.JTextField();
        inputRespuestaIncorrecta2 = new javax.swing.JTextField();
        inputRespuestaIncorrecta3 = new javax.swing.JTextField();
        panelDialogoFila4 = new javax.swing.JPanel();
        btnInsertar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        panelPrincipal = new javax.swing.JPanel();
        panelFila1 = new javax.swing.JPanel();
        listaCuestionarios = new javax.swing.JComboBox<>();
        listaCategorias = new javax.swing.JComboBox<>();
        panelFila2 = new javax.swing.JPanel();
        panelBotones = new javax.swing.JPanel();
        btnCrear = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnBorrarCuestionario = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnInsertarPregunta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPreguntas = new javax.swing.JTable();
        barraMenu = new javax.swing.JMenuBar();
        menuUsuario = new javax.swing.JMenu();
        opcionCerrarSesion = new javax.swing.JMenuItem();
        opcionModoJuego = new javax.swing.JMenuItem();
        menuAdministrador = new javax.swing.JMenu();
        opcionPreguntas = new javax.swing.JMenuItem();
        opcionCuestionarios = new javax.swing.JMenuItem();
        opcionCategorias = new javax.swing.JMenuItem();

        dialogoInformacionPregunta.setPreferredSize(new java.awt.Dimension(600, 400));

        panelInformacionPregunta.setLayout(new java.awt.GridLayout(3, 1));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 40));

        labelTextoPregunta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTextoPregunta.setForeground(new Color(255, 255, 255));
        labelTextoPregunta.setText("Aqui va el texto de la pregunta");
        labelTextoPregunta.setBorder(javax.swing.BorderFactory.createTitledBorder("Enunciado"));
        labelTextoPregunta.setHorizontalAlignment(SwingConstants.HORIZONTAL);
        labelTextoPregunta.setPreferredSize(new java.awt.Dimension(700, 50));
        jPanel1.add(labelTextoPregunta);

        labelCategoriaPregunta.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelCategoriaPregunta.setForeground(new Color(255, 255, 255));
        labelCategoriaPregunta.setText("Categoria");
        labelCategoriaPregunta.setPreferredSize(new java.awt.Dimension(200, 50));
        labelCategoriaPregunta.setBorder(javax.swing.BorderFactory.createTitledBorder("Categoria"));
        labelCategoriaPregunta.setHorizontalAlignment(SwingConstants.HORIZONTAL);
        jPanel1.add(labelCategoriaPregunta);

        panelInformacionPregunta.add(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(2, 4));

        labelRespuestaCorrecta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelRespuestaCorrecta.setForeground(new Color(255, 255, 255));
        labelRespuestaCorrecta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRespuestaCorrecta.setText("Respuesta Correcta");
        jPanel2.add(labelRespuestaCorrecta);

        labelRespuestaIncorrecta1Informacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelRespuestaIncorrecta1Informacion.setForeground(new Color(255, 255, 255));
        labelRespuestaIncorrecta1Informacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRespuestaIncorrecta1Informacion.setText("Respuesta Incorrecta 1");
        jPanel2.add(labelRespuestaIncorrecta1Informacion);

        labelRespuestaIncorrecta2Informacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelRespuestaIncorrecta2Informacion.setForeground(new Color(255, 255, 255));
        labelRespuestaIncorrecta2Informacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRespuestaIncorrecta2Informacion.setText("Respuesta Incorrecta 2");
        jPanel2.add(labelRespuestaIncorrecta2Informacion);

        labelRespuestaIncorrecta3Informacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelRespuestaIncorrecta3Informacion.setForeground(new Color(255, 255, 255));
        labelRespuestaIncorrecta3Informacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRespuestaIncorrecta3Informacion.setText("Respuesta Incorrecta 3");
        jPanel2.add(labelRespuestaIncorrecta3Informacion);

        textoRespuestaCorrecta.setEditable(false);
        textoRespuestaCorrecta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textoRespuestaCorrecta.setForeground(new Color(255, 255, 255));
        textoRespuestaCorrecta.setHorizontalAlignment(JTextField.CENTER);
        textoRespuestaCorrecta.setBackground(new Color(50, 255, 126, 100));
        jPanel2.add(textoRespuestaCorrecta);

        textoRespuestaIncorrecta1.setEditable(false);
        textoRespuestaIncorrecta1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textoRespuestaIncorrecta1.setForeground(new Color(255, 255, 255));
        textoRespuestaIncorrecta1.setHorizontalAlignment(JTextField.CENTER);
        textoRespuestaIncorrecta1.setBackground(new Color(255, 56, 56, 100));
        jPanel2.add(textoRespuestaIncorrecta1);

        textoRespuestaIncorrecta2.setEditable(false);
        textoRespuestaIncorrecta2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textoRespuestaIncorrecta2.setForeground(new Color(255, 255, 255));
        textoRespuestaIncorrecta2.setHorizontalAlignment(JTextField.CENTER);
        textoRespuestaIncorrecta2.setBackground(new Color(255, 56, 56, 100));
        jPanel2.add(textoRespuestaIncorrecta2);

        textoRespuestaIncorrecta3.setEditable(false);
        textoRespuestaIncorrecta3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textoRespuestaIncorrecta3.setForeground(new Color(255, 255, 255));
        textoRespuestaIncorrecta3.setHorizontalAlignment(JTextField.CENTER);
        textoRespuestaIncorrecta3.setBackground(new Color(255, 56, 56, 100));
        jPanel2.add(textoRespuestaIncorrecta3);

        panelInformacionPregunta.add(jPanel2);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 40));

        btnSalirDiaologoInformacion.setBackground(new Color(238, 82, 83));
        btnSalirDiaologoInformacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalirDiaologoInformacion.setForeground(new Color(0, 0, 0));
        btnSalirDiaologoInformacion.setText("Salir");
        btnSalirDiaologoInformacion.setPreferredSize(new java.awt.Dimension(200, 50));
        btnSalirDiaologoInformacion.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnSalirDiaologoInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirDiaologoInformacionActionPerformed(evt);
            }
        });
        jPanel3.add(btnSalirDiaologoInformacion);

        panelInformacionPregunta.add(jPanel3);

        javax.swing.GroupLayout dialogoInformacionPreguntaLayout = new javax.swing.GroupLayout(dialogoInformacionPregunta.getContentPane());
        dialogoInformacionPregunta.getContentPane().setLayout(dialogoInformacionPreguntaLayout);
        dialogoInformacionPreguntaLayout.setHorizontalGroup(
                dialogoInformacionPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelInformacionPregunta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
        );
        dialogoInformacionPreguntaLayout.setVerticalGroup(
                dialogoInformacionPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelInformacionPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelPrincipal1.setLayout(new java.awt.GridLayout(4, 1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new Color(255, 255, 255));
        jLabel1.setText("Preguntas");
        panelDialogoFila1.add(jLabel1);

        panelPrincipal1.add(panelDialogoFila1);

        panelDialogoFila2.setPreferredSize(new java.awt.Dimension(1000, 50));

        listaPreguntasDialogo.setEditable(true);
        listaPreguntasDialogo.setForeground(new Color(255, 255, 255));
        listaPreguntasDialogo.setMaximumRowCount(50);
        listaPreguntasDialogo.setPreferredSize(new java.awt.Dimension(600, 40));
        listaPreguntasDialogo.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent evt) {
                listaPreguntasDialogoItemListener(evt);
            }
        });
        panelDialogoFila2.add(listaPreguntasDialogo);

        listaCategoriasDialogo.setForeground(new Color(255, 255, 255));
        listaCategoriasDialogo.setPreferredSize(new java.awt.Dimension(200, 40));
        listaCategoriasDialogo.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent evt) {
                listaCategoriasDialogoItemListener(evt);
            }
        });

        panelDialogoFila2.add(listaCategoriasDialogo);

        panelPrincipal1.add(panelDialogoFila2);

        panelDialogoFila3.setLayout(new java.awt.GridLayout(2, 4));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Respuesta Correcta");
        panelDialogoFila3.add(jLabel2);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Respuesta Incorrecta 1");
        panelDialogoFila3.add(jLabel4);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Respuesta Incorrecta 2 ");
        panelDialogoFila3.add(jLabel3);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Respuesta Incorrecta 3");
        panelDialogoFila3.add(jLabel5);

        inputRespuestaCorrecta.setColumns(20);
        inputRespuestaCorrecta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputRespuestaCorrecta.setForeground(new Color(255, 255, 255));
        inputRespuestaCorrecta.setBackground(new Color(50, 255, 126, 100));
        inputRespuestaCorrecta.setHorizontalAlignment(SwingConstants.HORIZONTAL);
        panelDialogoFila3.add(inputRespuestaCorrecta);

        inputRespuestaIncorrecta1.setColumns(20);
        inputRespuestaIncorrecta1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputRespuestaIncorrecta1.setForeground(new Color(255, 255, 255));
        inputRespuestaIncorrecta1.setBackground(new Color(255, 56, 56, 100));
        inputRespuestaIncorrecta1.setHorizontalAlignment(SwingConstants.HORIZONTAL);
        panelDialogoFila3.add(inputRespuestaIncorrecta1);

        inputRespuestaIncorrecta2.setColumns(20);
        inputRespuestaIncorrecta2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputRespuestaIncorrecta2.setForeground(new Color(255, 255, 255));
        inputRespuestaIncorrecta2.setBackground(new Color(255, 56, 56, 100));
        inputRespuestaIncorrecta2.setHorizontalAlignment(SwingConstants.HORIZONTAL);
        panelDialogoFila3.add(inputRespuestaIncorrecta2);

        inputRespuestaIncorrecta3.setColumns(20);
        inputRespuestaIncorrecta3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputRespuestaIncorrecta3.setForeground(new Color(255, 255, 255));
        inputRespuestaIncorrecta3.setBackground(new Color(255, 56, 56, 100));
        inputRespuestaIncorrecta3.setHorizontalAlignment(SwingConstants.HORIZONTAL);
        panelDialogoFila3.add(inputRespuestaIncorrecta3);

        panelPrincipal1.add(panelDialogoFila3);

        panelDialogoFila4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 30));

        btnInsertar.setBackground(new Color(29, 209, 161));
        btnInsertar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInsertar.setForeground(new Color(0, 0, 0));
        btnInsertar.setText("Insertar");
        btnInsertar.setBorder(null);
        btnInsertar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsertar.setPreferredSize(new java.awt.Dimension(200, 60));
        btnInsertar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                btnInsertarActionListener(evt);
            }
        });
        panelDialogoFila4.add(btnInsertar);

        btnBuscar.setBackground(new Color(29, 209, 161));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscar.setForeground(new Color(0, 0, 0));
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(null);
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setPreferredSize(new java.awt.Dimension(200, 60));
        panelDialogoFila4.add(btnBuscar);

        btnSalir.setBackground(new Color(238, 82, 83));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalir.setForeground(new Color(0, 0, 0));
        btnSalir.setText("Salir");
        btnSalir.setBorder(null);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setPreferredSize(new java.awt.Dimension(200, 60));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        panelDialogoFila4.add(btnSalir);

        panelPrincipal1.add(panelDialogoFila4);

        javax.swing.GroupLayout dialogoPreguntasLayout = new javax.swing.GroupLayout(dialogoPreguntas.getContentPane());
        dialogoPreguntas.getContentPane().setLayout(dialogoPreguntasLayout);
        dialogoPreguntasLayout.setHorizontalGroup(
                dialogoPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelPrincipal1, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
        );
        dialogoPreguntasLayout.setVerticalGroup(
                dialogoPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dialogoPreguntasLayout.createSequentialGroup()
                                .addComponent(panelPrincipal1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setLayout(new java.awt.BorderLayout());

        panelFila1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 30));
        listaCuestionarios.setEditable(false);
        listaCuestionarios.setForeground(new Color(0, 0, 0));
        listaCuestionarios.setMaximumRowCount(50);
        listaCuestionarios.setPreferredSize(new java.awt.Dimension(600, 40));
        listaCuestionarios.setFont(new java.awt.Font("Segoe UI", 1, 14));
        listaCuestionarios.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent evt) {
                listaCuestionariosItemListener(evt);
            }
        });
        panelFila1.add(listaCuestionarios);

        listaCategorias.setPreferredSize(new java.awt.Dimension(200, 40));
        listaCategorias.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent evt) {
                listaCategoriasItemListener(evt);
            }
        });
        panelFila1.add(listaCategorias);

        panelPrincipal.add(panelFila1, java.awt.BorderLayout.PAGE_START);

        panelFila2.setLayout(new java.awt.BorderLayout());

        panelBotones.setPreferredSize(new java.awt.Dimension(200, 293));
        panelBotones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 30));

        btnCrear.setBackground(new Color(29, 209, 161));
        btnCrear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCrear.setForeground(new Color(0, 0, 0));
        btnCrear.setText("Crear");
        btnCrear.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnCrear.setPreferredSize(new java.awt.Dimension(150, 40));
        btnCrear.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                btnCrearActionListener(evt);
            }
        });
        panelBotones.add(btnCrear);
        btnInsertarPregunta.setBackground(new Color(29, 209, 161));
        btnInsertarPregunta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInsertarPregunta.setForeground(new Color(0, 0, 0));
        btnInsertarPregunta.setText("Añadir Pregunta");
        btnInsertarPregunta.setPreferredSize(new java.awt.Dimension(150, 40));
        btnInsertarPregunta.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnInsertarPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarPreguntaActionPerformed(evt);
            }
        });
        panelBotones.add(btnInsertarPregunta);

        btnBorrar.setBackground(new Color(238, 82, 83));
        btnBorrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBorrar.setForeground(new Color(0, 0, 0));
        btnBorrar.setText("Borrar Pregunta");
        btnBorrar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnBorrar.setPreferredSize(new java.awt.Dimension(150, 40));
        btnBorrar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                btnBorrarActionListener(evt);
            }
        });
        panelBotones.add(btnBorrar);

        btnModificar.setBackground(new Color(238, 82, 83));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnModificar.setForeground(new Color(0, 0, 0));
        btnModificar.setText("Modificar");
        btnModificar.setPreferredSize(new java.awt.Dimension(150, 40));
        btnModificar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnModificar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                btnModificarActionListener(evt);
            }
        });
        panelBotones.add(btnModificar);

        btnBorrarCuestionario.setBackground(new Color(238, 82, 83));
        btnBorrarCuestionario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBorrarCuestionario.setForeground(new Color(0, 0, 0));
        btnBorrarCuestionario.setText("Borrar");
        btnBorrarCuestionario.setPreferredSize(new java.awt.Dimension(150, 40));
        btnBorrarCuestionario.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnBorrarCuestionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarCuestionarioActionListener(evt);
            }
        });
        panelBotones.add(btnBorrarCuestionario);

        panelFila2.add(panelBotones, java.awt.BorderLayout.LINE_END);

        tablaPreguntas.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null}
                },
                new String[]{
                        "Pregunta", "Respuesta Correcta", "Respuesta Incorrecta 1", "Respuesta Incorrecta 2", "Respuesta Incorrecta 3"
                }
        ) {
            Class[] types = new Class[]{
                    String.class, String.class, String.class, String.class, String.class
            };
            boolean[] canEdit = new boolean[]{
                    false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        tablaPreguntas.addMouseListener(new MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPreguntasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPreguntas);

        panelFila2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        panelPrincipal.add(panelFila2, java.awt.BorderLayout.CENTER);

        menuUsuario.setText("Usuario");

        opcionModoJuego.setText("Seleccionar Modo de juego");
        opcionModoJuego.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_E, ActionEvent.ALT_MASK));
        opcionModoJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionModoJuegoActionPerformed(evt);
            }
        });
        menuUsuario.add(opcionModoJuego);

        barraMenu.add(menuUsuario);
        opcionCerrarSesion.setText("Cerrar sesion");
        opcionCerrarSesion.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_X, ActionEvent.ALT_MASK));
        opcionCerrarSesion.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                opcionCerrarSesionActionListener(evt);
            }
        });
        menuUsuario.add(opcionCerrarSesion);


        menuAdministrador.setText("Administrador");

        opcionPreguntas.setText("Preguntas");
        opcionPreguntas.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_P, ActionEvent.ALT_MASK));
        opcionPreguntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionPreguntasActionPerformed(evt);
            }
        });
        menuAdministrador.add(opcionPreguntas);

        opcionCuestionarios.setText("Cuestionarios");
        opcionCuestionarios.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_C, ActionEvent.ALT_MASK));
        opcionCuestionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionCuestionariosActionPerformed(evt);
            }
        });
        menuAdministrador.add(opcionCuestionarios);

        opcionCategorias.setText("Categorias");
        opcionCategorias.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_A, ActionEvent.ALT_MASK));
        opcionCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionCategoriasActionPerformed(evt);
            }
        });
        menuAdministrador.add(opcionCategorias);

        barraMenu.add(menuAdministrador);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                                .addContainerGap())
        );
        for (String e : GestionCategorias.obtenerCategorias()) {
            listaCategorias.addItem(e);
            listaCategoriasDialogo.addItem(e);
        }
        actualizarCuestionarios();
        actualizarPreguntasDialogo();
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarCuestionarioActionListener(ActionEvent evt) {
        int id = GestionCuestionarios.obtenerId((String) listaCuestionarios.getSelectedItem());
        if(JOptionPane.showConfirmDialog(null, "¿Estas seguro de que quieres borrar la categoria?", "¿Estas seguro?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) != 0){
            return;
        }
        if(GestionCuestionarios.borrar(id)){
            JOptionPane.showMessageDialog(this, "Cuestionario borrado correctamente", "Correcto", JOptionPane.INFORMATION_MESSAGE);
            listaCuestionarios.removeItem(listaCuestionarios.getSelectedItem().toString());
        }else{
            JOptionPane.showMessageDialog(this, "No se ha podido borrar el cuestionario", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnModificarActionListener(ActionEvent evt) {
        //obtenemos los datos antiguos del cuestionario
        String nombreAntiguo = (String) listaCuestionarios.getSelectedItem();
        String descripcionAntigua = GestionCuestionarios.obtenerDescripcion(nombreAntiguo);
        //se los pasamos al dialogo
        DialogoDatosCategoriaCuestionario.setDescripcion(descripcionAntigua);
        DialogoDatosCategoriaCuestionario.setNombre(nombreAntiguo);
        //obtenemos el id del cuestionario
        int id = GestionCuestionarios.obtenerId(nombreAntiguo);
        //mostramos el dialogo indicandole que no restablezca los datos
        DialogoDatosCategoriaCuestionario.mostrarDialogo(false);
        //obtenemos los nuevos datos del cuestionario
        String nombre = DialogoDatosCategoriaCuestionario.getNombre();
        String descripcion = DialogoDatosCategoriaCuestionario.getDescripcion();
        if(nombre == null || descripcion == null){//se comprueba que no sean nulos porque el usuario ha cerrado el dialogo con la X
            return;
        }
        if (nombre.equals("") || descripcion.equals("")) {//se comprueba que los datos no esten vacios
            JOptionPane.showMessageDialog(this, "datos erroneos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        /**
         * Creamos el objeto cuestionario que contiene:
         *      el id del cuestionario que vamos a modificar
         *      el nombre nuevo del cuestionario
         *      la nueva descripcion del cuestionario
         */
        Cuestionario c = new Cuestionario(id, nombre, descripcion);
        //realizamos la modificacion y mostramos el mensaje correspondiente
        if (GestionCuestionarios.modificar(c)) {
            JOptionPane.showMessageDialog(this, "Cuestionario modificado correctamente", "Correcto", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No se ha podido modificar el cuestionario", "Error", JOptionPane.ERROR_MESSAGE);
        }
        //obtenemos la posicion del cuestionario seleccionado
        int posicionCuestionario = listaCategorias.getSelectedIndex();
        listaCuestionarios.removeAllItems(); // vaciamos la lista
        actualizarCuestionarios(); //la volvemos a llenar
        /*seleccionamos el elemento que se encuentra en la misma posicion que el que acabamos de modificar,
          de esta manera se vera reflejada la modificacion en la lista y el usuario no notara el cambio
         */
        listaCuestionarios.setSelectedIndex(posicionCuestionario);
    }

    private void btnBorrarActionListener(ActionEvent evt) {
        int posicion = tablaPreguntas.getSelectedRow();
        int idPregunta = GestionPreguntas.obtenerId((String) modelo.getValueAt(posicion, 0));
        int idCuestionario = GestionCuestionarios.obtenerId((String) listaCuestionarios.getSelectedItem());
        if (JOptionPane.showConfirmDialog(null, "¿Estas seguro de que quieres realizar la accion?", "¿Estas seguro?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) != 0) {
            return;
        }
        if (GestionCuestionarios.borrarPregunta(idCuestionario, idPregunta)) {
            JOptionPane.showMessageDialog(this, "Pregunta borrada correctamente", "Correcto", JOptionPane.INFORMATION_MESSAGE);
            GestionCuestionarios.colocarPreguntas(tablaPreguntas, (String) listaCuestionarios.getSelectedItem());
        } else {
            JOptionPane.showMessageDialog(this, "No se ha podido borrar la pregunta", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnInsertarActionListener(ActionEvent evt) {
        int idCuestionario = GestionCuestionarios.obtenerId(listaCuestionarios.getSelectedItem().toString());
        int idPregunta = GestionPreguntas.obtenerId(listaPreguntasDialogo.getSelectedItem().toString());
        if (idCuestionario == -1 || idPregunta == -1) {
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (JOptionPane.showConfirmDialog(null, "¿Estas seguro de que quieres realizar la accion?", "¿Estas seguro?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == 0) {
            if (GestionCuestionarios.insertarPregunta(idCuestionario, idPregunta)) {
                JOptionPane.showMessageDialog(this, "Pregunta insertada correctamente", "Correcto", JOptionPane.INFORMATION_MESSAGE);
                GestionCuestionarios.colocarPreguntas(tablaPreguntas, (String) listaCuestionarios.getSelectedItem());
            } else {
                JOptionPane.showMessageDialog(this, "No se ha podido añadir la pregunta", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        dialogoPreguntas.dispose();
    }

    private void listaPreguntasDialogoItemListener(ItemEvent evt) {
        try {
            String[] datos = GestionPreguntas.obtenerRespuestas(listaPreguntasDialogo.getSelectedItem().toString());
            if (datos == null) {
                System.out.println("Nuloo");
                return;
            }
            GestionPreguntas.colocarRespuesta(inputRespuestaCorrecta, datos[0]);
            GestionPreguntas.colocarRespuesta(inputRespuestaIncorrecta1, datos[1]);
            GestionPreguntas.colocarRespuesta(inputRespuestaIncorrecta2, datos[2]);
            GestionPreguntas.colocarRespuesta(inputRespuestaIncorrecta3, datos[3]);
        } catch (NullPointerException | ArrayIndexOutOfBoundsException ex) {
            /*
             * En caso de que se seleccione una categoria sin preguntas, ocurrira una expecion
             * porque no hay nada en la lista desplegable, entonces vaciamos las respuestas
             * para que no se queden las respuestas de la pregunta anterior
             */
            inputRespuestaCorrecta.setText("");
            inputRespuestaIncorrecta1.setText("");
            inputRespuestaIncorrecta2.setText("");
            inputRespuestaIncorrecta3.setText("");
        }
    }

    private void listaCategoriasDialogoItemListener(ItemEvent evt) {
        actualizarPreguntasDialogo();
    }

    private void listaCategoriasItemListener(ItemEvent evt) {
        listaCuestionarios.removeAllItems();
        actualizarCuestionarios();
    }

    /**
     * Este metodo actualiza los cuestionarios de la lista desplegable
     *
     * @author Fernando
     */
    private void actualizarCuestionarios() {
        ArrayList<String> cuestionarios = GestionCuestionarios.obtenerCuestionarios(listaCategorias.getSelectedItem().toString());
        for (String s : cuestionarios) {
            if (!contieneElemento(s)) {
                listaCuestionarios.addItem(s);
            }
        }
    }

    /**
     * Este metodo actualiza las preguntas del dialogo que se muestra cuando se
     * pulsa el boton de añadir pregunta
     *
     * @author Fernando
     */
    public void actualizarPreguntasDialogo() {
        listaPreguntasDialogo.removeAllItems();
        ArrayList<String[]> preguntas = GestionPreguntas.obtenerPreguntas(listaCategoriasDialogo.getSelectedItem().toString());
        for (String[] arr : preguntas) {
            listaPreguntasDialogo.addItem(arr[0]);
        }
    }

    /**
     * Este metodo permite comprobar si existe un elemento en la
     * lista de los cuestionarios
     *
     * @param elemento es el elemento que queremos comprobar
     * @return true si existe, false si no
     * @author Fernando
     */
    public boolean contieneElemento(String elemento) {
        ComboBoxModel<String> modelo = listaCuestionarios.getModel();
        for (int i = 0; i < modelo.getSize(); i++) {
            if (modelo.getElementAt(i).equals(elemento)) {
                return true;
            }
        }
        return false;
    }

    private void listaCuestionariosItemListener(ItemEvent evt) {
        actualizarCuestionarios();
        if (listaCuestionarios.getSelectedItem() != null) {
            modelo = GestionCuestionarios.colocarPreguntas(tablaPreguntas, listaCuestionarios.getSelectedItem().toString());
        }
    }

    private void btnCrearActionListener(ActionEvent evt) {
        DialogoDatosCategoriaCuestionario.mostrarDialogo(true);
        String nombre = DialogoDatosCategoriaCuestionario.getNombre();
        String descripcion = DialogoDatosCategoriaCuestionario.getDescripcion();
        int id = GestionCategorias.obtenerIdCategoria(listaCategorias.getSelectedItem().toString());
        if (descripcion == null || nombre == null) { // se comprueba que los datos sean nulos
            return;
        } else if (GestionCuestionarios.existeCuestionario(nombre)) { // se comprueba que ya existe un cuestionario con ese nombre
            JOptionPane.showMessageDialog(this, "Ya existe un cuestionario con ese nombre", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (GestionCuestionarios.insertarCuestionario(id, nombre, descripcion) > 0) {// se comprueba si se ha insertado en la base de datos o no
            JOptionPane.showMessageDialog(this, "Cuestionario insertado correctamente", "Correcto", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No se ha podido insertar el cuestionario", "Error", JOptionPane.ERROR_MESSAGE);
        }
        actualizarCuestionarios();

    }

    private void opcionCerrarSesionActionListener(ActionEvent evt) {
        VentanaLogin frame = new VentanaLogin();
        frame.setVisible(true);
        dispose();

    }

    private void tablaPreguntasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        //obtenemos la posicion de la fila que se ha pulsado
        int posicion = tablaPreguntas.getSelectedRow();
        //obtenemos los datos de la pregunta
        String enunciado = (String) modelo.getValueAt(posicion, 0);
        String respuestaCorrecta = (String) modelo.getValueAt(posicion, 1);
        String respuestaIncorrecta1 = (String) modelo.getValueAt(posicion, 2);
        String respuestaIncorrecta2 = (String) modelo.getValueAt(posicion, 3);
        String respuestaIncorrecta3 = (String) modelo.getValueAt(posicion, 4);
        //colocamos el enunciado de la pregunta
        GestionPreguntas.colocarEnunciadoPregunta(labelTextoPregunta, enunciado);
        //colocamos la categoria en su label correspondiente
        labelCategoriaPregunta.setText(GestionCategorias.obtenerCategoriaPregunta(enunciado));
        //colocamos las respuestas de la pregunta
        GestionPreguntas.colocarRespuesta(textoRespuestaCorrecta, respuestaCorrecta);
        GestionPreguntas.colocarRespuesta(textoRespuestaIncorrecta1, respuestaIncorrecta1);
        GestionPreguntas.colocarRespuesta(textoRespuestaIncorrecta2, respuestaIncorrecta2);
        GestionPreguntas.colocarRespuesta(textoRespuestaIncorrecta3, respuestaIncorrecta3);

        dialogoInformacionPregunta.setSize(1000, 500);
        dialogoInformacionPregunta.show();
    }//GEN-LAST:event_jTable1MouseClicked

    private void opcionModoJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionModoJuegoActionPerformed
        VentanaSeleccionarModoJuego ventana = new VentanaSeleccionarModoJuego();
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_opcionModoJuegoActionPerformed

    private void opcionPreguntasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionPreguntasActionPerformed
        VentanaAdministrarPreguntas ventana = new VentanaAdministrarPreguntas();
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_opcionPreguntasActionPerformed

    private void opcionCuestionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionCuestionariosActionPerformed
        VentanaAdministrarCuestionarios ventana = new VentanaAdministrarCuestionarios();
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_opcionCuestionariosActionPerformed

    private void opcionCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionCategoriasActionPerformed
        VentanaAdministrarCategorias ventana = new VentanaAdministrarCategorias();
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_opcionCategoriasActionPerformed

    private void btnInsertarPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarPreguntaActionPerformed
        dialogoPreguntas.setSize(1000, 500);
        dialogoPreguntas.show();
    }//GEN-LAST:event_btnInsertarPreguntaActionPerformed

    private void btnVaciarDialogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaciarDialogoActionPerformed

    }//GEN-LAST:event_btnVaciarDialogoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dialogoPreguntas.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSalirDiaologoInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirDiaologoInformacionActionPerformed
        dialogoInformacionPregunta.dispose();
    }//GEN-LAST:event_btnSalirDiaologoInformacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrarCuestionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrarCuestionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrarCuestionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrarCuestionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAdministrarCuestionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBorrarCuestionario;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnInsertarPregunta;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSalirDiaologoInformacion;
    private javax.swing.JDialog dialogoInformacionPregunta;
    private javax.swing.JDialog dialogoPreguntas;
    private javax.swing.JTextField inputRespuestaCorrecta;
    private javax.swing.JTextField inputRespuestaIncorrecta1;
    private javax.swing.JTextField inputRespuestaIncorrecta2;
    private javax.swing.JTextField inputRespuestaIncorrecta3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPreguntas;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel labelCategoriaPregunta;
    private javax.swing.JLabel labelRespuestaCorrecta;
    private javax.swing.JLabel labelRespuestaIncorrecta1Informacion;
    private javax.swing.JLabel labelRespuestaIncorrecta2Informacion;
    private javax.swing.JLabel labelRespuestaIncorrecta3Informacion;
    private javax.swing.JLabel labelTextoPregunta;
    private javax.swing.JComboBox<String> listaCategorias;
    private javax.swing.JComboBox<String> listaCategoriasDialogo;
    private javax.swing.JComboBox<String> listaCuestionarios;
    private javax.swing.JComboBox<String> listaPreguntasDialogo;
    private javax.swing.JMenu menuAdministrador;
    private javax.swing.JMenu menuUsuario;
    private javax.swing.JMenuItem opcionCerrarSesion;
    private javax.swing.JMenuItem opcionCategorias;
    private javax.swing.JMenuItem opcionCuestionarios;
    private javax.swing.JMenuItem opcionModoJuego;
    private javax.swing.JMenuItem opcionPreguntas;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelDialogoFila1;
    private javax.swing.JPanel panelDialogoFila2;
    private javax.swing.JPanel panelDialogoFila3;
    private javax.swing.JPanel panelDialogoFila4;
    private javax.swing.JPanel panelFila1;
    private javax.swing.JPanel panelFila2;
    private javax.swing.JPanel panelInformacionPregunta;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelPrincipal1;
    private javax.swing.JTextField textoRespuestaCorrecta;
    private javax.swing.JTextField textoRespuestaIncorrecta1;
    private javax.swing.JTextField textoRespuestaIncorrecta2;
    private javax.swing.JTextField textoRespuestaIncorrecta3;
    // End of variables declaration//GEN-END:variables
}
